name: Continuous Integration
env:
   APPLICATION_NAME    : "NyFlask"
   DEPLOY_PACKAGE_NAME : "flask-deploy-ver_${{ github.sha }}"
on:
  push:
    branches:
      - main
jobs:

  my_testing:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Print Hello Messages1
      run: echo "Hello World from testing job"

    - name: Execute few commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.APPLICATTION_NAME }}"
    - name: List current folder
      run: ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v2

    - name: set up Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "14"
    
    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Create deployment artifact
      run: |
        mkdir artifacts
        cp -r dist artifacts/
        cp package.json artifacts/
        cp package-lock.json artifacts/

    - name: List current folder
      run: ls -la
    
  my_deploy:
    runs-on: ubuntu-latest  
    needs: [my_testing]
    env: 
      VAR1 : "This is job Level Variable1"
      VAR2 : "This is job Level Variable2"

    steps: 
    - name: Print Hello Messages
      run: echo "Hello World from Deploy job"

    - name: Print env vars
      run : | 
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR" 
      env :
        LOCAL_VAR: "This is Super local Environment variable"  
       
      
    - name: Printing Deployment package
      run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE-NAME }}"

    - name: Lets test some packages 
      run : aws --version
    
    - name: test zip
      run: zip
